adapters:
  - http
  - ws
debug: false
enableVerify: true
verifyKey: DEBUGTHEWORLD
singleMode: false
cacheSize: 4096
adapterSettings:
  ws:
    host: localhost

    port: 8088

    reservedSyncId: msg
  http:
    host: localhost

    port: 8088

    cors: [*]