# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QLabel { color: rgb(255, 255, 255); }\n"
"/* Top Buttons */\n"
"#TopButtons .QPushButton { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#TopButtons .QPushButton:hover { background-color: rgb(44, 49, 57); border-style: solid; border-radius: 4px; }\n"
"#TopButtons .QPushButton:pressed { background-color: rgb(23, 26, 30); border-style: solid; border-radius: 4px; }\n"
"\n"
"QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* LineEdit */\n"
"QLineEdit {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTextBrowser */\n"
"QTextBrowser {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QTextBrowser  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QTextBrowser  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QTextBrowser:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QTextBrowser:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setGeometry(QtCore.QRect(10, 10, 791, 481))
        self.verticalWidget.setStyleSheet("#UpBg {    background-color: rgb(33, 37, 43);}\n"
"#MainBg{    background-color: rgb(44, 49, 58);}")
        self.verticalWidget.setObjectName("verticalWidget")
        self.all = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.all.setContentsMargins(0, 0, 0, 0)
        self.all.setSpacing(0)
        self.all.setObjectName("all")
        self.UpBg = QtWidgets.QFrame(self.verticalWidget)
        self.UpBg.setObjectName("UpBg")
        self.aaa = QtWidgets.QHBoxLayout(self.UpBg)
        self.aaa.setContentsMargins(10, 5, 10, 1)
        self.aaa.setSpacing(1)
        self.aaa.setObjectName("aaa")
        self.label = QtWidgets.QLabel(self.UpBg)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setSizeIncrement(QtCore.QSize(50, 0))
        self.label.setObjectName("label")
        self.aaa.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.aaa.addItem(spacerItem)
        self.TopButtons = QtWidgets.QFrame(self.UpBg)
        self.TopButtons.setObjectName("TopButtons")
        self.TopBtn = QtWidgets.QHBoxLayout(self.TopButtons)
        self.TopBtn.setContentsMargins(0, 5, 0, 5)
        self.TopBtn.setSpacing(5)
        self.TopBtn.setObjectName("TopBtn")
        self.miniWindow = QtWidgets.QPushButton(self.TopButtons)
        self.miniWindow.setMinimumSize(QtCore.QSize(28, 28))
        self.miniWindow.setMaximumSize(QtCore.QSize(28, 28))
        self.miniWindow.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/imgFile/icon_minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.miniWindow.setIcon(icon)
        self.miniWindow.setObjectName("miniWindow")
        self.TopBtn.addWidget(self.miniWindow)
        self.closeWindow = QtWidgets.QPushButton(self.TopButtons)
        self.closeWindow.setMinimumSize(QtCore.QSize(28, 28))
        self.closeWindow.setMaximumSize(QtCore.QSize(28, 28))
        self.closeWindow.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/imgFile/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeWindow.setIcon(icon1)
        self.closeWindow.setObjectName("closeWindow")
        self.TopBtn.addWidget(self.closeWindow)
        self.aaa.addWidget(self.TopButtons)
        self.all.addWidget(self.UpBg)
        self.MainBg = QtWidgets.QFrame(self.verticalWidget)
        self.MainBg.setObjectName("MainBg")
        self.bnbb = QtWidgets.QHBoxLayout(self.MainBg)
        self.bnbb.setObjectName("bnbb")
        self.stackedWidget = QtWidgets.QStackedWidget(self.MainBg)
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.mcl_output = QtWidgets.QTextBrowser(self.stackedWidgetPage1)
        self.mcl_output.setGeometry(QtCore.QRect(18, 210, 751, 200))
        self.mcl_output.setObjectName("mcl_output")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.stackedWidgetPage1)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 265, 132))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(40, -1, 40, -1)
        self.horizontalLayout_4.setSpacing(50)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mclRun = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.mclRun.setMinimumSize(QtCore.QSize(0, 20))
        self.mclRun.setObjectName("mclRun")
        self.horizontalLayout_4.addWidget(self.mclRun)
        self.mclStop = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.mclStop.setEnabled(False)
        self.mclStop.setMinimumSize(QtCore.QSize(0, 20))
        self.mclStop.setObjectName("mclStop")
        self.horizontalLayout_4.addWidget(self.mclStop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 54, 12))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QtWidgets.QWidget()
        self.stackedWidgetPage2.setObjectName("stackedWidgetPage2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.stackedWidgetPage2)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 210, 789, 200))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.stackedWidget.addWidget(self.stackedWidgetPage2)
        self.bnbb.addWidget(self.stackedWidget)
        self.all.addWidget(self.MainBg)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Test1"))
        self.label_2.setText(_translate("MainWindow", "当前QQ号："))
        self.lineEdit.setText(_translate("MainWindow", "1234567890"))
        self.mclRun.setText(_translate("MainWindow", "启动"))
        self.mclStop.setText(_translate("MainWindow", "stopppp"))
        self.label_3.setText(_translate("MainWindow", "Mcl输出"))
from UiFile import icon
